### ISSUE TITLE
Website not working

### ISSUE THREAD

**Issue by caspertone2003** [Chuyu-Team/Dism-Multi-language#702] opened 2019-08-20 15:52 UTC
https://www.chuyu.me/  - no correct certificate
http://www.chuyu.me/ - error 404

Thanks

**Comment by xmprocat** [comment] 2019-08-20 17:37
can not updata the app

**Comment by sgseo** [comment] 2019-08-21 07:00
https://www.chuyu.me/zh-Hans/ 404 Not Found!!!

**Comment by MouriNaruto** [comment] 2019-08-21 09:07
Because of the political reasons, the website will be offline for several days, weeks or months.

**Comment by mcc85s** [comment] 2019-08-21 15:10
You can call them political reasons... but your project is committing espionage.

Here's my proof.

Fix the problems your tool is generating with DCOM. I've seen some of the 'problems' your software is causing. I had a lot of high hopes about your project because it is exceptionally useful...

However, the fact that it is corrupting all of the images that it touches, AND, allows you people to 'access whatever machine its used on'.

I've seen it.

You can either admit that "the picture I just posted is a pretty telling sign that you're ignoring what I said."

Which constitutes as 'malicious action'.

![image](https://user-images.githubusercontent.com/44849131/63444111-fbcd6a00-c403-11e9-89d9-6aba1df6a12e.png)

**Comment by MouriNaruto** [comment] 2019-08-21 17:01
> You can call them political reasons... but your project is committing espionage.
> Here's my proof.
> Fix the problems your tool is generating with DCOM. I've seen some of the 'problems' your software is causing. I had a lot of high hopes about your project because it is exceptionally useful...
> However, the fact that it is corrupting all of the images that it touches, AND, allows you people to 'access whatever machine its used on'.
> I've seen it.
> You can either admit that "the picture I just posted is a pretty telling sign that you're ignoring what I said."
> Which constitutes as 'malicious action'.

The DCOM issues are not related to Dism++. So I have closed that issue.

**Comment by MouriNaruto** [comment] 2019-08-21 17:04
Reference about political reasons: http://www.xinhuanet.com/politics/2019-06/11/c_1210156243.htm

So I closed this issue.

**Closed by MouriNaruto** 2019-08-21 17:04 UTC

**Comment by mcc85s** [comment] 2019-08-21 21:15
Where's your proof that they're not related? "The DCOM Issues are not related, so I've closed that issue without showing any proof that supports the theory that I just pulled out of my ass."

That's basically what that sounds like. I showed solid proof of it. I made changes to how the system configures the GPO's before it even boots, and guess what? All of those things I changed showed up with the DCOM tool that I created, so if you want to tell me that they're not related, maybe you can tell me where you earned your Microsoft Certifcation, because I have mine and I'm telling you, this software is causing those issues.

**Comment by MouriNaruto** [comment] 2019-08-21 23:27
Note:
If someone don't trust this project, they should not use this project.
We reject the malicious suspicion of others.
So I block that user.

**Comment by MouriNaruto** [comment] 2019-09-02 07:19
Please goto #717

**Comment by verdy-p** [comment] 2019-09-05 23:33
Please respect the announcement made publicly in the website "Open source is not only a spirit, but also a symbol of strength". Do not use any form of private close development to do what ever you want even if the project has now a newcoming leader (whose trust is still debatable, as it was never announced by the previous author, and the change was not described at all).
The recent issues about invalid certificates and inclusion of spywares in the website after the change, most probably caused by the newcoming leader, has seriously compromized the level of trust and this tool which was clean was recently banned as malicious and dangerous by various security tools around the world (and that was also never explained to existing users about what they should do if the site was ever compromized by a third-party hack: consider that security is a REQUIREMENT, not an option, and security/privacy issues are now to be taken seriously, they are even required now by laws around the world even if they are still not enforced by the People's Republic of China).
I areally suggest you reread and fix the many issues that exist in the Licencing terms: the English text included in the software (used also as the actual source for all other translations, is full of contradictions or non-sense, or lot of confusion, don't belive that Chinese can be easily translated to English with automatic translators, consider contacting another Chinese contributor that correctly knows English, e.g. in Hong Kong, don't do what other Chinese companies are delivering to the world with unreadable notice of uses). Having a correct English text is now a priority if you ever want again to restore an international trust. Also you'll need to provide summaries of changes in English (those in Chinese are completely untranslatable and make no sense). You really need a true bilingual English-Chinese contributor to your project, and probably advices from a lawyer for the licencing terms (but for now the old announcement "Open source is not only a spirit, but also a symbol of strength" has never been true, based on approximation and no clear delimitation of the project and who owns it and controls it: "open source" means also a community that can effectively supervize and give a review without being banned by a single leader making also arbitrary interpretation of a single message, taking any senseful critic as if it was insulting, and then reacting with insults).
Note: Microsoft/GitHub was informed and visibly took action. I was never intending to break the project but the critic was about reinforcing the trust we can give to the project after it was seriously compromized (and there's still work to do to restore that trust, starting by respecting their existing community of contributors, and managing the sunmitted issues more seriously than just closing all of them: may be there were many issues, but if the project must go on, there will be time to manage and schedule all of them even if there is a newcoming leader, who now must present himself and explain the new goals of the project)

**Comment by MouriNaruto** [comment] 2019-09-06 03:02
Dism++ is a partial open source project. (Closed part license should follow mingkuang's Chinese text. Open source part should follow the MIT license.)

**Also, I am not the new leader.** So I can't make Dism++ 100% open source. (Today, Dism++'s open source style is more similar as Microsoft's. We make some libraries open source, but the others not.)
