### ISSUE TITLE
English translation issue

### ISSUE THREAD

**Issue by rnbrito** [Chuyu-Team/Dism-Multi-language#697] opened 2019-07-31 05:01 UTC
I've corrected the line 1046 of the english translation. The target at that line is wrong because of the second chinese char (陆) and the correct one is (录). I've translated by screenshotting and then zooming (using MSPAINT) to then use the live translation of Google Translator app on my phone. I've couldn't select that text at the program. Then, having the approximated translation, I've searched the language file for the key words. After comparing visually every char to find the wrong one, I've had to visually search the right char at another line that appeared similar to the char on the program interface.
That may be wrong on the other translations...

To make that easy, why not add a tooltip on every translated item, showing the original text (in chinese) and the line number of the XML language file that was used to translate that, and also if that translation wasn't found at the XML, the text could be written in red or the tooltip could have an error message about that.

The right properties of that line are:
Target="登录界面默认打开小键盘（by IT之家）"
Link="Enable keypad when login (by ITHome)"

And for the tooltip idea, it could have the following text:
登录界面默认打开小键盘（by IT之家）(en.xml:1046)

**Comment by verdy-p** [comment] 2019-07-31 09:27
The tooltip is not a good idea, unless it is enabled by a specific option/setting.
Tooltips are also used for the interface and are also translated.
So if the setting is enabled, I think that the translated items should just be modified by adding the line number as a leading text
And for Link="Enable keypad when login (by ITHome)"
we would get the text:
 "[en:1046]Enable keypad when login (by ITHome)"

The main problem is for the fallback (Chinese), because they are not in the translated resource files but in the C source code of the application and have no other simple references than the Chinese text itself (which is then difficult to locate).

And when this Chinese text changes in the source code, there's no way to match the existing translations easily, the new Chinese text will then appear as a fallback in ALL other translations, that must be fixed manually in their Target="*" line and then the following Link="*" line also marked as being "fuzzy".

It's frequent to see new Chinese texts appearing that are impossible to locate (and because the C source code of the application is also not published in the repository, we cannot guess what changed, each time we need to contact the support.

There's one exception: Chinese text which are part of selectable custom filters (which are in the repository) and not part of the C source itself.

The other problem is for some resources that are not free text (e.g. a few items at top of resource files that contain font names/sizes for the UI: these cannot be modified by adding a prefix, as they would no longer work as intended).

**Comment by MouriNaruto** [comment] 2019-08-24 16:38
Closed temporarily, we will reopen again if have response.

**Closed by MouriNaruto** 2019-08-24 16:38 UTC
